from logic import clearScreen, time, os, sys, typingPrint, typingInput

# function to ask to play again or not
def play_again():
    print("\nDo you want to play again? (y or n)")

    # convert players input to lowercase
    answer = input(">").lower()

    if "y" in answer:
        start()
    else:
        exit()

# game_over function accepts an argument called "reason"
def game_over(reason):
    # print the "reason" in a new line (\n)
    print("/n" + reason)
    print("Game Over!")
    # ask player to play again or not
    play_again()

def start():
    typingPrint("\nFADE IN")
    print("")
    # time.sleep(2)
    typingPrint("\nThunderous sounds of a massive naval barrage are heard. The power is astonishing. ")
    typingPrint("\nIt roars through the body, blows back the hair and rattles the ears. A swarm of ")
    typingPrint("\nlanding craft heads directly into a nightmare. Massive explosions from German ")
    typingPrint("\nartillery shells and mined obstacles tear apart the beach. Hundreds of German ")
    typingPrint("\nmachine guns, loaded with tracers, pour out a red snowstorm of bullets. ")
    print("")
    # time.sleep(2)
    typingPrint("\nOMAHA BEACH - NORMANDY - DAWN")
    print("")
    # time.sleep(2)
    print("")
    typingPrint("The roar of naval guns continues but now we see them firing. Huge fifteen inch guns.")
    print("")
    # time.sleep(2)
    print("")
    # time.sleep(2)
    typingPrint("OFFSHORE")
    print("")
    # time.sleep(3)
    print("")
    typingPrint("OMAHA BEACH, NORMANDY")
    print("")
    # time.sleep(1)
    typingPrint("JUNE 6, 1994")
    print("")
    # time.sleep(1)
    typingPrint("0600 HOURS")
    print("")
    # time.sleep(3)
    print("")
    typingPrint("HUNDREDS OF LANDING CRAFT")
    print("")
    typingPrint("\nEach holding thirty men, near the beaches.")
    print("")
    # time.sleep(3)
    print("")
    typingPrint("THE CLIFFS")
    print("")
    typingPrint("\nAt the far end of the beach, a ninety-foot cliff. Topped by ")
    typingPrint("\nbunkers. Ringed by fortified machine gun nests. A clear lineof- ")
    typingPrint("\nfire down the entire beach. ")
    print("")
    # time.sleep(3)
    print("")
    typingPrint("TEN LANDING CRAFT")
    print("")
    typingPrint("\nMake their way toward the base of the cliffs. Running a ")
    typingPrint("\ngaunlet of explosions. ")
    print("")
    # time.sleep(3)
    print("")
    typingPrint("THE FOLLOWING IS BASED ON A TRUE STORY")
    print("")
    # time.sleep(3)
    print("")
    typingPrint("THE LEAD LANDING CRAFT")
    print("")
    typingPrint("\nPlows through the waves.")
    print("")
    # time.sleep(3)
    print("")
    typingPrint("THE CAMERA MOVES PAST THE FACES OF THE MEN")
    print("")
    typingPrint("\nBoys. Most are eighteen or nineteen years old. Tough. Well- ")
    typingPrint("\ntrained. Trying to block out fury around them. ")
    print("")
    # time.sleep(3)
    print("")
    typingPrint("A DIRECT HIT ON A NEARBY LANDING CRAFT")
    print("")
    typingPrint("\nA huge explosion of fuel, fire, metal and flesh. ")
    print("")
    # time.sleep(3)
    print("")
    typingPrint("THE LEADING CRAFT")
    print("")
    typingPrint("\nThe Motorman holds his course. Shells explode around them. ")
    typingPrint("\nFlaming oil burns on the water. Cannon fire smashes into the ")
    typingPrint("\nbow. ")
    print("")
    # time.sleep(3)
    print("")
    typingPrint("THE MOTORMAN IS RIPPED TO BITS")
    print("")
    typingPrint("\nBlood and flesh shower the men behind him.  The mate takes ")
    typingPrint("\nthe controls. ")
    print("")
    # time.sleep(3)
    print("")
    typingPrint("A YOUNG SOLDIER")
    print("")
    typingPrint("\nHis face covered with the remains of the motorman. Starts to ")
    typingPrint("\nlose it. Begins to shudder and weep. His name is DeLancey. ")
    print("")
    #time.sleep(3)
    print("")
    typingPrint("THE BOYS AROUND HIM")
    print("")
    typingPrint("\nDo their best to stare straight ahead.  But the fear infects ")
    typingPrint("\nthem. It starts to spread. ")
    print("")
    # time.sleep(3)
    print("")
    typingPrint("A FIGURE")
    print("")
    typingPrint("\nPushes through the men.  Puts himself in front of Delancy. ")
    typingPrint("\nThe figure is captain John Miller.  Early thirties.  By far ")
    typingPrint("\nthe oldest man on the craft.  Relaxed, battle-hardened, ")
    typingPrint("\npowerful, ignoring the hell around them.  He smiles, puts a ")
    typingPrint("\ncigar in his mouth, strikes a match on the front of ")
    typingPrint("\nDelancy's helmet and lights the cigar. ")
    typingPrint("\nDeLancey tries to look away but Miller grips him by the jaw ")
    typingPrint("\nand forces him to lock eyes. Miller smiles. DeLancey is ")
    typingPrint("\nterrified.")
    print("")
    typingPrint("\nDELANCY")
    print("")
    typingPrint("Captain, are we all gonna die? ")
    print("")
    typingPrint("\nMILLER")
    print("")
    typingPrint("Hell no, two-thirds, tops.")
    print("")
    typingPrint("\nDELANCEY")
    print("")
    typingPrint("Oh, Jesus...")
    print("")
    # time.sleep(3)
    typingPrint("\nMILLER")
    print("")
    typingPrint("\nI want every one of you to look at ")
    typingPrint("\nthe man on your left. Now look at ")
    typingPrint("\nthe man on your right. Feel sorry ")
    typingPrint("\nthey're going to get it, you're ")
    typingPrint("\nnot going to get a scratch. ")
    print("")
    # time.sleep(3)
    typingPrint("\nA few, including DeLancey, manage thin smiles. Miller ")
    typingPrint("\nreleases his grip on DeLancey who moves his jaw as if to see ")
    typingPrint("\nif it's broken. Miller pats him on the cheek and moves on to ")
    typingPrint("\nthe bow.")
    print("")
    # time.sleep(3)
    print("")
    typingPrint("\nMILLER")
    print("")
    typingPrint("Looks over the gunwale at the hell in front of them.")
    print("")
    typingPrint("\nPAN DOWN TO MILLER'S HAND")
    print("")
    typingPrint("\nIt quivers in fear. Miller glances around, see that none of ")
    typingPrint("\nthe men have noticed. He stares at his hand as if it belongs ")
    typingPrint("\nto someone else. It stops shaking. He turns his eyes back to ")
    typingPrint("\nthe objective.")

    # dog_green_sector()

def dog_green_sector(): 
    print("")   
    typingPrint("\nDOG GREEN SECTOR, OMAHA BEACH")
    time.sleep(2)
    print("*waves crashing, ocean water hits the front of the U boat spitting water over*")
    time.sleep(2)
    print("*you hear mortal fire exploding over the distance.*")
    time.sleep(2)
    print("*hands shaking, holding on to your rifle*")
    time.sleep(2)
    print("*an alarm chimes, and the U boat hatch drops*")
    time.sleep(2)
    print("*imediately machine gune fire rips through the front line killing everyone in front*")
    time.sleep(3)
    dog_green_options()

def dog_green_options():
    print("\n'option '1' - Stay put, wait for orders...")
    print("\n'option '2' - Climb over the ledge into the cold waters...")
    print("\ntype '1' or '2'")

    answer = input(">").lower()

    if answer == "1":
        game_over("You were mowed down by machine gun fire...")
    elif answer == "2":
        cold_water()
    else:
        print("Failure is not an option solder!")
        dog_green_options()

def cold_water():
    print("*you plunge into the cold ocean water*")
    print("*bullets zing by left and right*")
    print("*bodys sink below you, the water glows red*")
    print("*you fight against the currents and make it above water, your boots hit the sand...*")
    time.sleep(3)

def cold_water_options():
    print("\n")
    print("\n'option '1' - Stay put, wait for orders...")
    print("\n'option '2' - Climb over the ledge into the cold waters...")
    print("\ntype '1' or '2'")





start()